### ISSUE TITLE
Is there any method for loading data to "Entity"?

### ISSUE THREAD

**Issue by shortcutsReallyHelp** [naglfar666/amper#1]
I v got situation where I call $SomeRepo->findByName($name). It returns me an array. The question is how load this array data to Entity class in order to use save()
Here It is what I have now
```php
$user = $someRepo->findByName($name);
//$user is array
//in order to update user I have to load data piece by piece myself
$userEntity = new UserEntity();
$userEntity->setId($user['id'])
$userEntity->setName($user['name']);
// ... some good stuff I want to update
$userEntity->save();

```
Is it possible to do the same action doing this way?
```php
//I want to update only name
$user = $someRepo->findByName($name);
$user->setName($new_name);
$user->save();

```

**Comment by leonardomaier** [comment]
@almatsboom did you test it?

**Comment by naglfar666** [comment]
This functionality is in progress, you can offer a better solution.

**Comment by leonardomaier** [comment]
@naglfar666 it is supposed to have similarity with Eloquent's functionality?

I mean, if you do something like this, the variable `$user` could get a UserEntity instance and would be able to update the record directly:

`$user = $someRepo->findByName($name);`
`$user->setName('Test')->save()`

**Comment by shortcutsReallyHelp** [comment]
I guess I expressed my thoughts wrong way =| I apologize for that.
I wanted to say then 
```php
//I want to update only name
$user = $someRepo->findByName($name); //Entitiy
$user->setName($new_name);
$someRepo->save($user);
```

**Comment by shortcutsReallyHelp** [comment]
I think this way would be great as well
```php
$userData = $someRepo->findByName($name); //Array
$user = new UserEntity($userData);
//OR
$user = new UserEntity();
$user->load($userData);
$user->setName($new_name);
$someRepo->save($user);
```

**Comment by naglfar666** [comment]
@almatsboom closed this with PR
