### ISSUE TITLE
 Automatically generate configuration files

### ISSUE THREAD

**Issue by leonardomaier** [naglfar666/amper#2]
Currently you need to configure the project structure manually, but it would be great if there were any commands or scripts that generated the project's initial folders and files.

**Comment by naglfar666** [comment]
Thank's for your feedback, added Installer class, that would initiate project's structure. Now you can create install.php file in root directory and then run it:
`
define('GLOBAL_DIR', __DIR__);
require_once(GLOBAL_DIR.'/vendor/autoload.php');
$Installer = new Amper\Installer;
$Installer->start();
`
Added this to README
